#//////////////////////////////////////////////////////////////////////////////
#/
#/ Copyright (c) 2018-2019 Ethinza Inc, All rights reserved
#/
#/ This file contains TRADE SECRETs of ETHINZA INC and is CONFIDENTIAL.
#/ Without written consent from ETHINZA INC, it is prohibited to disclose or
#/ reproduce its contents, or to manufacture, use or sell it in whole or part.
#/ Any reproduction of this file without written consent of ETHINZA INC is a 
#/ violation of the copyright laws and is subject to civil liability and 
#/ criminal prosecution.
#/
#//////////////////////////////////////////////////////////////////////////////

TARGET   =	ethinza
SRCS     =	\
			base/memory.cpp \
			base/thread.cpp \
			\
			service/ethhandler.cpp \
			service/logmanager.cpp \
			service/threadmonitor.cpp \
			\
			utility/osinterface.cpp \
			utility/stringutility.cpp \
			utility/stringbuilder.cpp \
			utility/fileutility.cpp \
			\
			protocol/discovery.cpp \
			protocol/protocol.cpp \
			protocol/resource.cpp \
			# Add additional files here

CFLAGS  +=
#LDFLAGS += 

# Include the library makefile.
include $(ETHINZA_DIR)/make/libs.mk
